### PR TITLE
Moved all include installs to top level include dir

### PR DESCRIPTION
**Pull request by thejta**
Signed-off-by: Jason Albert <albertj@us.ibm.com>

### CODE REVIEW

**Comment by thejta** [comment]
The only thing that wasn't clear to me is there is a scripts dir that fapi2 was installing with the includes.  That didn't seem proper to move to the new top level `include` dir, so I left those where they were.

If something else should be done with them, let me know and I'll include it here.

**Comment by mklight** [comment]
yeah, seems like scripts staying where they are is a good idea

**Comment by lkammath** [comment]
Looks good to me

**Comment by thejta** [comment]
Should the scripts keep going where they are or should they get installed into bin?  If that was done, then the `ext` dir could go away completely.

**Comment by mklight** [comment]
could have a high level scripts directory maybe

**Comment by thejta** [comment]
> could have a high level scripts directory maybe

In the second change set I moved the scripts to the bin directory.  I figured that was a standard place for anything executable and it didn't require creating a new top level dir that didn't exist.  Let me know if you want it changed.  The top level now looks like:
```
$ ls install
bin  help  include  ppc64le
```

**Comment by kahnevan** [comment]
> > could have a high level scripts directory maybe
> 
> In the second change set I moved the scripts to the bin directory. I figured that was a standard place for anything executable and it didn't require creating a new top level dir that didn't exist. Let me know if you want it changed. The top level now looks like:
> 
> ```
> $ ls install
> bin  help  include  ppc64le
> ```

This makes sense to me.  I like the structure of it.

**Pull request merged**
